name: base_kit_tester
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  base_kit_package:
    path: ../base_kit_package
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-ExtraLight.ttf
          weight: 100 # Thin
        - asset: fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200 # ExtraLight
        - asset: fonts/nunito/Nunito-Light.ttf
          weight: 300 # Light
        - asset: fonts/nunito/Nunito-Regular.ttf
          weight: 400 # Regular
        - asset: fonts/nunito/Nunito-Medium.ttf
          weight: 500 # Medium
        - asset: fonts/nunito/Nunito-SemiBold.ttf
          weight: 600 # SemiBold
        - asset: fonts/nunito/Nunito-Bold.ttf
          weight: 700 # Bold
        - asset: fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800 # ExtraBold
        - asset: fonts/nunito/Nunito-Black.ttf
          weight: 900 # Black

