targets:
  $default:
    sources:
      include:
        - pubspec.yaml
        - $package$
        - lib/**
      exclude:
        - example/**
        - test/**
        - integration_test/**
        - "**/ephemeral/**"
        - "**/.plugin_symlinks/**"

