name: flutter_base_kit
description: "A comprehensive Flutter development kit with base classes, utilities, and common patterns for faster app development."
version: 1.3.0

homepage: https://okladnoj-bio.web.app/
repository: https://github.com/Okladnoj/flutter_base_kit
issue_tracker: https://github.com/Okladnoj/flutter_base_kit/issues

screenshots:
  - description: "flutter base kit"
    path: docs/flutter_base_kit-logo.png

environment:
  sdk: ^3.4.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  logger: ^2.6.1
  freezed_annotation: ^3.1.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  path: ^1.9.1
  args: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  source_gen: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
keywords:
  - flutter
  - template
  - boilerplate

topics:
  - search
  - template
  - boilerplate
  - routing
  - dependency-injection

executables:
  flutter_base_kit: flutter_base_kit
  fbkit: flutter_base_kit

license: MIT
